---
galaxy_info:
  author: tonyskidmore
  description: configure user jumphost environment
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - system
dependencies: []

